### PR TITLE
Rework regulator, improve wifi connect times

### PR DESCRIPTION
**Pull request by alexmohr**
* Regulator now uses a linear function to calculate open time
* Open/Close valve now share some code
* Reworked wifi manager and added fast connect

### CODE REVIEW

**Comment by Anycubic** [comment]
Very good! I'll test this in the week end!

**Comment by alexmohr** [comment]
fyi @Anycubic here is the overhauled regulator. I think it tends to overshoot a bit. At least it did with a 10 minute wait time. With 5 minutes between checks it seems to work fine, at least for small temperature differences. I'll have to test it a bit more in the next couple of days. If you want to play with timing check out https://github.com/alexmohr/open-heat/blob/overhaul-regulator/src/heating/RadiatorValve.cpp#L89

**Comment by alexmohr** [comment]
Oh you where faster with commenting the MR than I could mention you :smile:

**Comment by Anycubic** [comment]
I'd like to share some thoughts about using the 18650 shield you mentioned in the read me. Does Github allows to send private messages? I don't want to abuse this thread for non code related things :-)

**Comment by alexmohr** [comment]
No GitHub does not allow sending private messages. Send me an email at git@mohr.io

**Comment by Anycubic** [comment]
> No GitHub does not allow sending private messages. Send me an email at [git@mohr.io](mailto:git@mohr.io)

I wrote you from giuseppe@mirasole.org

**Comment by alexmohr** [comment]
Your mail must have been lost somewhere. I can't find it anywhere. You could also open a new issue to discuss your ideas.

**Comment by Anycubic** [comment]
Have a look in spam, it's there 100%. BTW I will also open a issue

**Comment by Anycubic** [comment]
Have you ever had this issue? Get set temperature shows nothing. I had to restart HA and it happened.
Tried to restart MQTT, HA, nothing. Deleted and pasted.again the mqtt section in HA config, had it reappeared, restarted HA and disappeared again!
Screenshot_2021-11-21-11-36-48-797_io homeassistant companion android~2

**Comment by alexmohr** [comment]
This will happen when you restart home assistant. The set temperature will be updated in home assistant as soon as the device will publish it again. Just wait 15 minutes with a turned on device and it will be shown. 
I could sent the messages from the device with retain flag and this won't happen again.

**Comment by Anycubic** [comment]
I did everything that you said and nothing worked. I also deleted the mqtt queue on the broker but still not working

**Pull request merged**
