### PR TITLE
Config portal

### PR DESCRIPTION
**Pull request by alexmohr**
Rework the configuration portal

### CODE REVIEW

**Comment by alexmohr** [comment]
Fixes #16

**Comment by alexmohr** [comment]
FYI @Anycubic when this PR will be merged the configuration will be cleared and wifi settings and so on have to created again. Maybe the configuration will be changed to json at some point to prevent breaking changes like this. The voltage divider also now uses 10M ohm and 3.3M ohm to prevent draining the battery. You can keep 100k and 33k if you want because the relation between the resistors and therefore the calculation stays the same.

**Comment by Anycubic** [comment]
> FYI @Anycubic when this PR will be merged the configuration will be cleared and wifi settings and so on have to created again. Maybe the configuration will be changed to json at some point to prevent breaking changes like this. The voltage divider also now uses 10M ohm and 3.3M ohm to prevent draining the battery. You can keep 100k and 33k if you want because the relation between the resistors and therefore the calculation stays the same.

Which branch do you advice I should use? Or did you merge everything in Dev? I saw a lot of activity!

**Comment by alexmohr** [comment]
> Which branch do you advice I should use? Or did you merge everything in Dev? I saw a lot of activity!

Almost everything is merged onto dev. This branch replaces the configuration portal and a few thing related to the webinterface. There are no functional changes to heating (only formatting). I only informed you about this branch, so you won't be surprised when I merge this that you have to configure everything again.
I will merge this in the next couple of days.

**Comment by Anycubic** [comment]
Hostname does not stick:

**Comment by alexmohr** [comment]
It sticks, it's just not displayed in the web frontend. fixed in #f9ed2dd

**Comment by Anycubic** [comment]
Something weird happened both on dev and config-portal branch, "off" command is never acquired on the valve will never switch off (stays always on heat, valve will never close)

**Comment by Anycubic** [comment]
that's DEV branch

```
[20:06:57][INFO]  Connecting MultiWifi...
[20:07:03][INFO]  Wifi connected:
[20:07:03]	Time: 2300
[20:07:03]	SSID: Mirabello
[20:07:03]	RSSI=-59
[20:07:03]	Channel: 1
[20:07:03]	IP address: 192.168.1.103
[20:07:03][INFO]  Running MQTT setup
[20:07:03][INFO]  MQTT topic: papa/, topic len: 5
[20:07:03][INFO]  MQTT subscribed to topic: papa/debug/enable
[20:07:04][INFO]  MQTT subscribed to topic: papa/mode/set
[20:07:04][INFO]  MQTT subscribed to topic: papa/modemsleep/set
[20:07:04][DEBUG] Updating RTCMemory
[20:07:04][INFO]  Set new modem sleep time 300000
[20:07:04][INFO]  MQTT subscribed to topic: papa/temperature/target/set
[20:07:04][INFO]  MQTT subscribed to topic: papa/debug/loglevel
[20:07:04][DEBUG] MQTT send '21.24' in topic 'papa/temperature/measured/get'
[20:07:04][DEBUG] MQTT send '51.77' in topic 'papa/humidity/measured/get'
[20:07:04][DEBUG] MQTT send '300000' in topic 'papa/modemsleep/get'
[20:07:04][DEBUG] MQTT send '0.00' in topic 'papa/battery/percent'
[20:07:04][DEBUG] MQTT send '0.86' in topic 'papa/battery/voltage'
[20:07:04][DEBUG] Updating RTCMemory
[20:07:04][DEBUG] trying to reach temperature: 21.000000
[20:07:04][DEBUG] Predicted temp 63.72 in 150000 ms, predict part: 42.48
[20:07:04][DEBUG] Updating RTCMemory
[20:07:04][DEBUG] Updating RTCMemory
[20:07:04][DEBUG] Updating RTCMemory
[20:07:04][DEBUG] Heating is turned off, disable heating
[20:07:04][INFO]  DEBUG: 0
[20:07:04][DEBUG] **Sleep times: valveSleep: 4294954697**, mqttSleep: 299972
[20:07:04][DEBUG] Starting deep sleep for: 299966
[20:07:04][INFO]  Sleeping for 299966 ms
[20:07:04][DEBUG] Updating RTCMemory
```
Sleep times: valveSleep: 4294954697 = 198 days?

**Comment by alexmohr** [comment]
`4294954697` sleep time to prevent waking up for heating when it's disabled anyways. 
I'll simplify this whole mode switching a bit as it's overly complicated.

**Comment by Anycubic** [comment]
> `4294954697` sleep time to prevent waking up for heating when it's disabled anyways. I'll simplify this whole mode switching a bit as it's overly complicated.

I had the feeling that this was the purpose, but there problem it's still there, the valve will not switch off after the "off" command is issued

**Comment by alexmohr** [comment]
it's apparent from the logs. I have an idea on how to fix this. I'll simplify the mode switching logic as it doesn't need to be that complicated.

**Pull request merged**
